version: "3"
services:
  chatbot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/opt/blabberbandit/backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://10.0.138.121:27017
