name: Docker Compose Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute commands over ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.BACKENDSECRET }}
        script: |
          cd /home/ec2-user/blabber-bandit-backend
          git pull
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml up -d

    - name: Cleanup
      if: always()
      run: docker-compose -f docker-compose.prod.yml down
